### ISSUE TITLE
[make-buildable] Schematic not working

### ISSUE THREAD

**Issue by dzena** [trellisorg/platform#12]
Steps I do:

- `nx g @trellisorg/make-buildable:migrate (I have nx globally installed)`
- `What project would you like to migrate? material`
- `What kind of library is this? angular`
- `If this is an Angular lib, what configurations would you like to create? (separated by a comma) production`

The exception thrown:
`Property 'libType' does not match the schema. 'angular' should be a 'undefined'.`

Part of the workspace with the lib in question:
![Screenshot 2020-12-23 at 13 32 49](https://user-images.githubusercontent.com/3988902/102996550-9885a780-4523-11eb-8e90-1133fb322bde.png)

Thanks!

Edit:
I guess this PR (https://github.com/trellisorg/platform/pull/11) will address this issue. 
I apologise, didn't take a look at the PRs first.

**Comment by Stonepaw** [comment]
Thanks for the issues, we've now merged in that pr and released version 0.0.10 which fixes this issue. Please upgrade to v0.0.10 and enjoy your buildable libraries!
