### ISSUE TITLE
It is not an issue. Just a request to update to angular 14

### ISSUE THREAD

**Issue by kyrolus** [trellisorg/platform#181]
Could you please update the package to support angular 14

**Comment by yharaskrik** [comment]
> Could you please update the package to support angular 14

Hi @kyrolus which package are you referring to? This repository has multiple packages in it.

**Comment by kyrolus** [comment]
@yharaskrik  This one @trellisorg/ngrx-universal-rehydrate

**Comment by yharaskrik** [comment]
> @yharaskrik  This one @trellisorg/ngrx-universal-rehydrate

Just on vacation right now. I'll do it when I get back on Monday!

**Comment by yharaskrik** [comment]
PR is more than welcome though!

**Comment by kyrolus** [comment]
> > @yharaskrik  This one @trellisorg/ngrx-universal-rehydrate
> 
> Just on vacation right now. I'll do it when I get back on Monday!

OK. I hope to enjoy your vacation.




> PR is more than welcome though!

I do not understand.

**Comment by yharaskrik** [comment]
> > > @yharaskrik  This one @trellisorg/ngrx-universal-rehydrate
> > 
> > Just on vacation right now. I'll do it when I get back on Monday!
> 
> OK. I hope to enjoy your vacation.
> 
> 
> 
> 
> > PR is more than welcome though!
> 
> I do not understand.

Feel free to open a pull request with the suggested changes needed to release the library for angular 14 and then I can. Cut a version when I'm back. I haven't looked at the code in a while so I'm not sure what is needed.

**Comment by yharaskrik** [comment]
Closed via version v0.0.14

https://www.npmjs.com/package/@trellisorg/ngrx-universal-rehydrate/v/0.0.14

**Comment by kyroluskamal** [comment]
Thank you very much.

**Comment by kyrolus** [comment]
Thank you very much
