### ISSUE TITLE
NgrxUniversalRehydrateBrowserModule doesn't exist

### ISSUE THREAD

**Issue by kyroluskamal** [trellisorg/platform#185]
First, I want to thank you for updating this great package. 

After update, I can't find the NgrxUniversalRehydrateBrowserModule. Actually, I can't find the browser folder in node_modules

![image](https://user-images.githubusercontent.com/37916625/180624685-faa49385-2f52-48ed-b668-2fe9fdd85506.png)

So, could you please fix this issue.

**Comment by yharaskrik** [comment]
There is no browser folder. You import it from @trellisorg/ngrx-universal-rehydrate if you get the public-api.ts file you will see it exported.

**Comment by kyroluskamal** [comment]
Ok. I find it. Thanks.
