### ISSUE TITLE
[ngrx-data-websocket-client] Additional query parameters?

### ISSUE THREAD

**Issue by sonnypgs** [trellisorg/platform#278]
Hi, first off, thanks a lot for creating this very helpful library :)

Sorry if this is not the right place to ask, but I was wondering if it's possible to somehow supply additional query parameters to the .getAll() service call.

For example I'd like to query my stories with an additional filter and userId param like so:

`this.storyWsService.getAll({ extraFilterParam: 'onlyRecent', userId: 123  });`
or
`this.storyWsService.getAll(options, { extraFilterParam: 'onlyRecent', userId: 123  });`

What would be the best way to achieve this (by forking)?
Thank you

**Comment by yharaskrik** [comment]
> Hi, first off, thanks a lot for creating this very helpful library :)
> 
> Sorry if this is not the right place to ask, but I was wondering if it's possible to somehow supply additional query parameters to the .getAll() service call.
> 
> For example I'd like to query my stories with an additional filter and userId param like so:
> 
> `this.storyWsService.getAll({ extraFilterParam: 'onlyRecent', userId: 123  });`
> or
> `this.storyWsService.getAll(options, { extraFilterParam: 'onlyRecent', userId: 123  });`
> 
> What would be the best way to achieve this (by forking)?
> Thank you

You would want to use `getWithQuery`

https://ngrx.io/guide/data/entity-dataservice

**Comment by sonnypgs** [comment]
Awesome, thank you very much @yharaskrik :)
