### ISSUE TITLE
`rx-dynamic-component@0.1.2` npm package peer dependencies

### ISSUE THREAD

**Issue by vitale232** [trellisorg/platform#32]
Thanks for sharing `rx-dynamic-component` with the community! Such a powerful little library.

I ran into some friction while testing out the npm package. I started with a brand new ng CLI app, and added the `@trellisorg/rx-dynamic-component` package to my dependencies. 

Like a good JS dev, I skipped over all of the peerDep warnings and started the dev server. The app was failing to compile, as I was missing two of the `peerDependencies`:

```
        "@angular/cdk": "12.2.2",
        "@ngrx/component": "^12.2.0",
```

FWIW, it looks like these [were added in a few days ago](https://github.com/trellisorg/platform/commit/de33dcabb2c61d245849124452b9b0784f1f9819#diff-a2f202c62174788e25eeffbda7150a3125447366965f325f1cadac1b6d7ffdd1).

Was this intentional? I'd probably be using the CDK in my app, but the `@ngrx/component` lib seems like an odd peer dep. It's [imported in the `LazyDynamicOutletModule`](https://github.com/trellisorg/platform/blob/master/packages/rx-dynamic-component/src/lib/lazy-dynamic-outlet/lazy-dynamic-outlet.module.ts), but I couldn't find where it's being used?

Thanks!

**Comment by yharaskrik** [comment]
Hey @vitale232! Thank you for reporting that! I believe I was trying something out and the dep must have ended up in there somehow. I will track it down and release a new version!

**Comment by yharaskrik** [comment]
` @trellisorg/rx-dynamic-component@0.1.3` has been released with the `@ngrx/component-store` dep removed, sorry about that and thanks for reporting! I am going to work and splitting the lib up a bit so that cdk is not a needed peer dep but thats for the future
