### ISSUE TITLE
rx-dynamic-component to support multiple dynamic components within a module

### ISSUE THREAD

**Issue by dwarakaprasad** [trellisorg/platform#369]
Based on what I see in [here](https://github.com/trellisorg/platform/blob/1d6d8a41db93b4142129238665b22761dc49166a/packages/rx-dynamic-component/src/lib/rx-dynamic-component.service.ts#L106), this only seem to support one dynamic component per module. This is a request to support multiple dynamic components within a module.

**Comment by yharaskrik** [comment]
> Based on what I see in [here](https://github.com/trellisorg/platform/blob/1d6d8a41db93b4142129238665b22761dc49166a/packages/rx-dynamic-component/src/lib/rx-dynamic-component.service.ts#L106), this only seem to support one dynamic component per module. This is a request to support multiple dynamic components within a module.

Correct, it currently only supports one per module. As much as I would like to support multiple we will actually be removing support for loading from a module entirely in the future. Please use Standalone Components if possible as they provide the exact same functionality but reduce the complexity of this library and are cleaner to manage in the codebase. They also do not suffer from DI hierarchy issues like the Module implementation does.

Let me know if you have anymore questions, thanks for opening the issue!

**Comment by dwarakaprasad** [comment]
thank you @yharaskrik for your quick response and yes make sense.
