### ISSUE TITLE
Buildable or publishable.. that is the question...

### ISSUE THREAD

**Issue by mackelito** [trellisorg/platform#41]
Not a bug in the plugin but I have been trying to the answer for some time now :P

Looking at the docs here.. https://nx.dev/l/r/structure/buildable-and-publishable-libraries
It's not clear when the libs should be buildable or not.. or should they ALWAYS be either buildable or publishable?

If not.. then when should a lib be NOT buildable/publishable?

**Comment by yharaskrik** [comment]
> Not a bug in the plugin but I have been trying to the answer for some time now :P
> 
> Looking at the docs here.. https://nx.dev/l/r/structure/buildable-and-publishable-libraries It's not clear when the libs should be buildable or not.. or should they ALWAYS be either buildable or publishable?
> 
> If not.. then when should a lib be NOT buildable/publishable?

Hey! Sorry I haven't been active maintaining this recently but I am back! Typically they should be buildable so you can leverage incremental compilation with Nx. Publishable is for when you are publishing to npm.
