### ISSUE TITLE
NgRx on SSR throws error when `strictStateSerializability` is set to `true`

### ISSUE THREAD

**Issue by exequiel09** [trellisorg/platform#45]
I think it's because the rehydration logic uses `Set` instead of plain old Array.

Error when running on SSR:
![Screen Shot 2022-02-18 at 4 14 04 PM](https://user-images.githubusercontent.com/1289472/154644083-02d070f0-0ed9-4790-9d74-11ce1d24f20f.png)

Potential source of issue:
https://github.com/trellisorg/platform/blob/b260e855ac9573fcd8de28e0ff9585065c0b9911/packages/ngrx-universal-rehydrate/src/lib/store.ts#L19

https://github.com/trellisorg/platform/blob/b260e855ac9573fcd8de28e0ff9585065c0b9911/packages/ngrx-universal-rehydrate/src/lib/store.ts#L33

The issue is gone when I set `strictStateSerializability` to `false`

**Comment by yharaskrik** [comment]
Sorry I just saw this! I will fix it and release an update.

**Comment by exequiel09** [comment]
Thanks! Will try it soon 🙏

**Comment by exequiel09** [comment]
Works like a charm @yharaskrik 🎊  Thanks 💯

**Comment by yharaskrik** [comment]
You are welcome!
